-- Run this in Supabase SQL Editor.
-- Auth users are created by Supabase Auth.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  credits integer not null default 10,
  plan text not null default 'free',
  created_at timestamptz not null default now()
);

create table if not exists public.ads (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  business_name text not null,
  product text not null,
  description text not null,
  target_customer text not null,
  platform text not null,
  goal text not null,
  tone text not null,
  campaign_name text not null,
  headline text not null,
  primary_text text not null,
  call_to_action text not null,
  social_caption text not null,
  image_prompt text not null,
  video_script text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.ai_usage (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  credits_used integer not null default 1,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.ads enable row level security;
alter table public.ai_usage enable row level security;

create policy "profiles own row" on public.profiles
for select using (auth.uid() = id);

create policy "profiles own update" on public.profiles
for update using (auth.uid() = id);

create policy "ads own rows" on public.ads
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "usage own rows" on public.ai_usage
for select using (auth.uid() = user_id);

create policy "usage own insert" on public.ai_usage
for insert with check (auth.uid() = user_id);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id) values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();